version: "3.0"
services:
  local:
    build: .
    environment:
      - BACKEND=${BACKEND:-gmail}
      - EMAIL
      - ORG_USER
      - PASSWORD
      - MEET_URL
      - VIDEO_NAME=${VIDEO_NAME:-video}
      - MAX_DURATION=${MAX_DURATION:-7200}
      - MIN_DURATION=${MIN_DURATION:-1800}
      - ASK_JOIN=${ASK_JOIN:-True}
      - FRAC_TO_EXIT=${FRAC_TO_EXIT:-0.90}
      - RESOLUTION=${RESOLUTION:-1920x1080}
    volumes:
      - ${OUTPUT_DIR:-./}:/output
    command: sh ./sources/driver.sh